---
abstract: 'Useful routines for generating HTML for use with Dancer + TT/Xslate ...'
author:
  - 'chenryn <rao.chenlin@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132830'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-TagHelper
no_index:
  directory:
    - t
    - inc
    - t
requires:
  Dancer: 0
  HTML::TagHelper: 0
  perl: 5.006
resources:
  repository: https://github.com/chenryn/Dancer-Plugin-TagHelper.git
version: 0.01
